site_name: Recipes
site_description: an example blog set up following the tutorial
site_url: http://recipes.ragedriven.dev

nav:
  - What's in Season: season.md

theme:
  name: material
  custom_dir: overrides
  features:
    # - navigation
    - navigation.tabs

plugins:
  - blog:
      archive: false
      blog_dir: .
      categories_allowed:
        - Autumn
        - Spring
        - Summer
        - Winter
      post_dir: "{blog}/recipes"
      post_excerpt: required
      post_readtime: false
  - search
  - tags

markdown_extensions:
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
