site_name: Rhys' Recipes
site_description: an example blog set up following the tutorial
site_url: http://www.example.com

nav:
  - What's in Season: season.md

theme:
  name: material
  features:
    # - navigation
    - navigation.tabs

plugins:
  - blog:
      archive: false
      blog_dir: .
      categories_allowed:
        - Autumn
        - Spring
        - Summer
        - Winter
      post_dir: "{blog}/recipes"
      post_excerpt: required
      post_readtime: false
  - search
  - tags